
var dd = [
  NormalModule {
    dependencies: [ [CommonJsRequireDependency], [RequireHeaderDependency] ],
    blocks: [],
    variables: [],
    type: 'javascript/auto',
    context: 'D:\\workplace\\webpack\\webpack-official\\debug\\src',
    debugId: 1000,
    hash: '3045ce7dea65c05965f8670626e795a0',
    renderedHash: '3045ce7dea65c05965f8',
    resolveOptions: {},
    factoryMeta: {},
    warnings: [],
    errors: [],
    buildMeta: { providedExports: true },
    buildInfo: {
      cacheable: true,
      fileDependencies: [Set],
      contextDependencies: Set(0) {},
      assets: undefined,
      assetsInfo: undefined,
      temporaryProvidedExports: false
    },
    reasons: [ [ModuleReason] ],
    _chunks: SortableSet(1) [Set] {
      [Chunk],
      _sortFn: [Function: sortById],
      _lastActiveSortFn: null,
      _cache: undefined,
      _cacheOrderIndependent: undefined
    },
    id: './src/index.js',
    index: 0,
    index2: 1,
    depth: 0,
    issuer: null,
    profile: undefined,
    prefetched: false,
    built: true,
    used: null,
    usedExports: null,
    optimizationBailout: [],
    _rewriteChunkInReasons: undefined,
    useSourceMap: false,
    _source: OriginalSource {
      _value: '/* eslint-disable prettier/prettier */\n' +
        'const {\n' +
        '  foo\n' +
        '} = require("./utils/mtest");\n' +
        '\n' +
        'console.log(foo(1, 3));\n' +
        "console.log('index---------------------');",
      _name: 'D:\\workplace\\webpack\\webpack-official\\node_modules\\babel-loader\\lib\\index.js!D:\\workplace\\webpack\\webpack-official\\debug\\src\\index.js'
    },
    request: 'D:\\workplace\\webpack\\webpack-official\\node_modules\\babel-loader\\lib\\index.js!D:\\workplace\\webpack\\webpack-official\\debug\\src\\index.js',
    userRequest: 'D:\\workplace\\webpack\\webpack-official\\debug\\src\\index.js',
    rawRequest: './src/index.js',
    binary: false,
    parser: Parser {
      _pluginCompat: [SyncBailHook],
      hooks: [Object],
      options: {},
      sourceType: 'auto',
      scope: undefined,
      state: undefined,
      comments: undefined
    },
    generator: JavascriptGenerator {},
    resource: 'D:\\workplace\\webpack\\webpack-official\\debug\\src\\index.js',
    matchResource: undefined,
    loaders: [ [Object] ],
    error: null,
    _sourceSize: null,
    _buildHash: '5df9808d8c6b0715e0ed2b97f2b14165',
    buildTimestamp: 1649235232472,
    _cachedSources: Map(1) { 'javascript' => [Object] },
    lineToLine: false,
    _lastSuccessfulBuildMeta: { providedExports: true },
    _ast: null
  },
  NormalModule {
    dependencies: [
      [HarmonyCompatibilityDependency],
      [HarmonyInitDependency],
      [HarmonyExportHeaderDependency],
      [HarmonyExportSpecifierDependency]
    ],
    blocks: [],
    variables: [],
    type: 'javascript/auto',
    context: 'D:\\workplace\\webpack\\webpack-official\\debug\\src\\utils',
    debugId: 1001,
    hash: '29cc87fff392e6ec410b426ee0fe0542',
    renderedHash: '29cc87fff392e6ec410b',
    resolveOptions: {},
    factoryMeta: {},
    warnings: [],
    errors: [],
    buildMeta: { exportsType: 'namespace', providedExports: [Array] },
    buildInfo: {
      cacheable: true,
      fileDependencies: [Set],
      contextDependencies: Set(0) {},
      assets: undefined,
      assetsInfo: undefined,
      strict: true,
      exportsArgument: '__webpack_exports__',
      temporaryProvidedExports: false
    },
    reasons: [ [ModuleReason] ],
    _chunks: SortableSet(1) [Set] {
      [Chunk],
      _sortFn: [Function: sortById],
      _lastActiveSortFn: null,
      _cache: undefined,
      _cacheOrderIndependent: undefined
    },
    id: './src/utils/mtest.js',
    index: 1,
    index2: 0,
    depth: 1,
    issuer: NormalModule {
      dependencies: [Array],
      blocks: [],
      variables: [],
      type: 'javascript/auto',
      context: 'D:\\workplace\\webpack\\webpack-official\\debug\\src',
      debugId: 1000,
      hash: '3045ce7dea65c05965f8670626e795a0',
      renderedHash: '3045ce7dea65c05965f8',
      resolveOptions: {},
      factoryMeta: {},
      warnings: [],
      errors: [],
      buildMeta: [Object],
      buildInfo: [Object],
      reasons: [Array],
      _chunks: [SortableSet [Set]],
      id: './src/index.js',
      index: 0,
      index2: 1,
      depth: 0,
      issuer: null,
      profile: undefined,
      prefetched: false,
      built: true,
      used: null,
      usedExports: null,
      optimizationBailout: [],
      _rewriteChunkInReasons: undefined,
      useSourceMap: false,
      _source: [OriginalSource],
      request: 'D:\\workplace\\webpack\\webpack-official\\node_modules\\babel-loader\\lib\\index.js!D:\\workplace\\webpack\\webpack-official\\debug\\src\\index.js',
      userRequest: 'D:\\workplace\\webpack\\webpack-official\\debug\\src\\index.js',
      rawRequest: './src/index.js',
      binary: false,
      parser: [Parser],
      generator: JavascriptGenerator {},
      resource: 'D:\\workplace\\webpack\\webpack-official\\debug\\src\\index.js',
      matchResource: undefined,
      loaders: [Array],
      error: null,
      _sourceSize: null,
      _buildHash: '5df9808d8c6b0715e0ed2b97f2b14165',
      buildTimestamp: 1649235232472,
      _cachedSources: [Map],
      lineToLine: false,
      _lastSuccessfulBuildMeta: [Object],
      _ast: null
    },
    profile: undefined,
    prefetched: false,
    built: true,
    used: null,
    usedExports: null,
    optimizationBailout: [],
    _rewriteChunkInReasons: undefined,
    useSourceMap: false,
    _source: OriginalSource {
      _value: '/* eslint-disable prettier/prettier */\n' +
        'export function foo(a, b) {\n' +
        '  console.log(a + b);\n' +
        "  console.log('mtest------------>>>>---------');\n" +
        '}',
      _name: 'D:\\workplace\\webpack\\webpack-official\\node_modules\\babel-loader\\lib\\index.js!D:\\workplace\\webpack\\webpack-official\\debug\\src\\utils\\mtest.js'
    },
    request: 'D:\\workplace\\webpack\\webpack-official\\node_modules\\babel-loader\\lib\\index.js!D:\\workplace\\webpack\\webpack-official\\debug\\src\\utils\\mtest.js',
    userRequest: 'D:\\workplace\\webpack\\webpack-official\\debug\\src\\utils\\mtest.js',
    rawRequest: './utils/mtest',
    binary: false,
    parser: Parser {
      _pluginCompat: [SyncBailHook],
      hooks: [Object],
      options: {},
      sourceType: 'auto',
      scope: undefined,
      state: undefined,
      comments: undefined
    },
    generator: JavascriptGenerator {},
    resource: 'D:\\workplace\\webpack\\webpack-official\\debug\\src\\utils\\mtest.js',
    matchResource: undefined,
    loaders: [ [Object] ],
    error: null,
    _sourceSize: null,
    _buildHash: 'f6202a2df209be79650e23058c0d2841',
    buildTimestamp: 1649235233048,
    _cachedSources: Map(1) { 'javascript' => [Object] },
    lineToLine: false,
    _lastSuccessfulBuildMeta: { exportsType: 'namespace', providedExports: [Array] },
    _ast: null
  }
]
